name: AWS Deploy

on:
  workflow_dispatch:
  # push:
  #   paths:
  #     - 'aws/**'
  #     - '!aws/readme.md'
  
env:
  FOLDERNAME: "aws"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

jobs:
  aws-deploy:
    name: aws-deploy-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: aws-deploy - Verify Terraform version
      run: terraform --version

    - name: aws-deploy - Terraform init
      run: terraform -chdir=$FOLDERNAME init -input=false

    - name: aws-deploy - Terraform validation
      run: terraform -chdir=$FOLDERNAME validate

    - name: aws-deploy - Terraform plan
      run: terraform -chdir=$FOLDERNAME plan -input=false

    - name: aws-deploy - Terraform apply
      run: terraform -chdir=$FOLDERNAME apply -auto-approve -input=false